dofile(vim.api.nvim_get_runtime_file("colors/vim.lua", false)[1])
local hi = function(name, val)
	val.force = true
	val.cterm = val.cterm or {} ---@type vim.api.keyset.highlight
	vim.api.nvim_set_hl(0, name, val)
end

local ferra_night = "#2b292d"
local ferra_ash = "#383539"
local ferra_umber = "#4d424b"
local ferra_bark = "#6F5D63"
local ferra_mist = "#D1D1E0"
local ferra_sage = "#B1B695"
local ferra_blush = "#fecdb2"
local ferra_coral = "#ffa07a"
local ferra_rose = "#F6B6C9"
local ferra_ember = "#e06b75"
local ferra_honey = "#F5D76E"

-- hi("@ncf.comment", { fg = "ferra_bark", modifiers = ["italic"] })
hi("@ncf.comment", { fg = ferra_bark })
hi("@ncf.constant", { fg = ferra_sage })
hi("@ncf.function", { fg = ferra_coral })
hi("@ncf.function.macro", { fg = ferra_mist })
hi("@ncf.keyword", { fg = ferra_mist })
hi("@ncf.operator", { fg = ferra_mist })
hi("@ncf.punctuation", { fg = ferra_blush })
hi("@ncf.string", { fg = ferra_sage })
hi("@ncf.type", { fg = ferra_rose })
hi("@ncf.variable", { fg = ferra_blush })
hi("@ncf.variable.builtin", { fg = ferra_rose })
hi("@ncf.tag", { fg = ferra_sage })
hi("@ncf.label", { fg = ferra_sage })
hi("@ncf.attribute", { fg = ferra_blush })
hi("@ncf.namespace", { fg = ferra_blush })
hi("@ncf.module", { fg = ferra_blush })

-- "markup.heading" = { fg = "ferra_sage", modifiers = ["bold"] }
-- "markup.heading.marker" = { fg = "ferra_bark" }
-- "markup.list" = { fg = "ferra_mist" }
-- "markup.bold" = { modifiers = ["bold"] }
-- "markup.italic" = { modifiers = ["italic"] }
-- "markup.strikethrough" = { modifiers = ["crossed_out"] }
-- "markup.link.url" = { fg = "ferra_rose", modifiers = ["underlined"] }
-- "markup.link.text" = { fg = "ferra_rose" }
-- "markup.quote" = { fg = "ferra_bark" }
-- "markup.raw" = { fg = "ferra_coral" }

hi('@ncf.ui.background', { bg = ferra_night })
hi('@ncf.ui.cursor', { fg = ferra_night, bg = ferra_blush })
hi('@ncf.ui.cursor.match', { fg = ferra_night, bg = ferra_bark })
hi('@ncf.ui.cursor.select', { fg = ferra_night, bg = ferra_rose })
hi('@ncf.ui.cursor.insert', { fg = ferra_night, bg = ferra_coral })
hi('@ncf.ui.linenr', { fg = ferra_bark })
hi('@ncf.ui.linenr.selected', { fg = ferra_blush })
hi('@ncf.ui.cursorline', { fg = ferra_blush, bg = ferra_ash })
hi('@ncf.ui.statusline', { fg = ferra_blush, bg = ferra_ash })
hi('@ncf.ui.statusline.inactive', { fg = ferra_bark, bg = ferra_ash })
hi('@ncf.ui.statusline.normal', { fg = ferra_ash, bg = ferra_blush })
hi('@ncf.ui.statusline.insert', { fg = ferra_ash, bg = ferra_coral })
hi('@ncf.ui.statusline.select', { fg = ferra_ash, bg = ferra_rose })
hi('@ncf.ui.popup', { fg = ferra_blush, bg = ferra_ash })
hi('@ncf.ui.window', { fg = ferra_bark, bg = ferra_night })
hi('@ncf.ui.help', { fg = ferra_blush, bg = ferra_ash })
hi('@ncf.ui.text', { fg = ferra_blush })
hi('@ncf.ui.text.focus', { fg = ferra_coral })
hi('@ncf.ui.menu', { fg = ferra_blush, bg = ferra_ash })
hi('@ncf.ui.menu.selected', { fg = ferra_coral, bg = ferra_ash })
hi('@ncf.ui.selection', { bg = ferra_umber })
hi('@ncf.ui.virtual', { fg = ferra_bark })
hi('@ncf.ui.virtual.whitespace', { fg = ferra_bark })
hi('@ncf.ui.virtual.ruler', { bg = ferra_ash })
hi('@ncf.ui.virtual.indent-guide', { fg = ferra_ash })
hi('@ncf.ui.virtual.inlay-hint', { fg = ferra_bark })

hi('@ncf.diff.plus', { fg = ferra_sage })
hi('@ncf.diff.delta', { fg = ferra_blush })
hi('@ncf.diff.minus', { fg = ferra_ember })

-- "error" = { fg = "ferra_ember" }
-- "warning" = { fg = "ferra_honey" }
-- "info" = { fg = "ferra_blush" }
-- "hint" = { fg = "ferra_blush" }

-- hi("@ncf.diagnostic.warning", { gui = 'undercurl', guisp = ferra_honey })
-- hi("@ncf.diagnostic.error", { gui = 'undercurl', guisp = ferra_ember })
-- hi("@ncf.diagnostic.info", { gui = 'undercurl', guisp = ferra_blush })
-- hi("@ncf.diagnostic.hint", { gui = 'undercurl', guisp = ferra_blush })
-- hi("@ncf.diagnostic.unnecessary", { modifiers = { "dim" } })
-- hi("@ncf.diagnostic.deprecated", { modifiers = { "crossed_out" } })

-- """"""""""""""""
-- " Vim builtins
-- """"""""""""""""

hi("CursorLineNr", { link = 'CursorLine' })
hi("PmenuMatch", { link = 'Pmenu' })
hi("PmenuMatchSel", { link = 'PmenuSel' })
hi("PmenuSel", { link = '@ncf.ui.menu.selected' })
hi("TabLineSel", { link = 'PmenuSel' })

-- "" UI
hi("ColorColumn", { link = '@ncf.ui.virtual.ruler' })
-- hi ( "ComplMatchIns", {} )
-- hi ( "Conceal", {} )
-- hi ( "CurSearch", {} )
-- hi ( "CursorColumn", {} )
hi("CursorLine", { link = '@ncf.ui.cursorline' })
hi("CursorLineFold", { link = 'CursorLine' })
hi("CursorLineSign", { link = 'CursorLine' })
hi("DiffAdd", { link = '@ncf.diff.plus' })
hi("DiffChange", { link = '@ncf.diff.delta' })
hi("DiffDelete", { link = '@ncf.diff.minus' })
-- hi ( "DiffText", {} )
-- hi ( "Directory ", {} )
-- hi ( "EndOfBuffer", {} )
-- hi ( "ErrorMsg", {} )
hi("FoldColumn", { link = 'LineNr' })
-- hi ( "Folded", {} )
-- hi ( "IncSearch", {} )
hi("LineNr", { link = '@ncf.ui.linenr.selected' })
hi("LineNrAbove", { link = '@ncf.ui.linenr' })
hi("LineNrBelow", { link = 'LineNrAbove' })
-- hi ( "ModeMsg", {} )
-- hi ( "MoreMsg", {} )
-- hi ( "MsgArea", {} )
-- hi ( "NonText", {} )
hi("Pmenu", { link = '@ncf.ui.menu' })
hi("PmenuExtra", { link = 'Pmenu' })
hi("PmenuExtraSel", { link = 'PmenuSel' })
hi("PmenuKind", { link = 'Pmenu' })
hi("PmenuKindSel", { link = 'PmenuSel' })
hi("PmenuSbar", { link = 'Pmenu' })
hi("PmenuThumb", { link = 'Pmenu' })
-- hi ( "Question", {} )
-- hi ( "QuickFixLine", {} )
-- hi ( "Search", {} )
hi("SignColumn", { link = 'LineNr' })
-- hi ( "SpecialKey", {} )
-- hi ( "SpellBad", {} )
-- hi ( "SpellCap", {} )
-- hi ( "SpellLocal", {} )
-- hi ( "SpellRare", {} )
hi("StatusLine", { link = '@ncf.ui.statusline' })
hi("StatusLineNC", { link = 'StatusLine' })
hi("StatusLineTerm", { link = 'StatusLine' })
hi("StatusLineTermNC", { link = 'StatusLine' })
-- hi ( "TabLine", {} )
-- hi ( "TabLineFill", {} )
-- hi ( "Title", {} )
-- hi ( "VertSplit", {} )
hi("Visual", { link = '@ncf.ui.selection' })
hi("VisualNOS", { link = 'Visual' })
-- hi ( "WarningMsg", {} )
hi("WildMenu", { link = 'Pmenu' })


-- """""""""""""
-- " Vim inits
-- """""""""""""

hi("Cursor", { link = '@ncf.ui.cursor' })
hi("Normal", { link = '@ncf.ui.background' })
-- hi ( "MessageWindow", {} )
-- hi ( "PopupNotification", {} )
hi("PopupSelected", { link = 'PmenuSel' })
-- hi ( "ToolbarButton", {} )
-- hi ( "ToolbarLine", {} )
hi("lCursor", { link = 'Cursor' })

-- "" UI
-- hi ( "MatchParen", {} )


-- """"""""""""""""""""""""""""
-- " Neovim specific builtins
-- """"""""""""""""""""""""""""

hi("TermCursor", { link = 'Cursor' })
hi("VisualNC", { link = 'Visual' })

-- "" UI
-- hi ( "FloatBorder", {} )
-- hi ( "FloatFooter", {} )
-- hi ( "FloatTitle", {} )
-- hi ( "MsgSeparator", {} )
hi("NormalFloat", { link = 'Normal' })
hi("NormalNC", { link = 'Normal' })
hi("Whitespace", { link = "@ncf.ui.virtual.whitespace" })
-- hi ( "WinBar", {} )
-- hi ( "WinBarNC", {} )
-- hi ( "WinSeparator", {} )


-- """""""""""""""""""""""""
-- " Neovim specific inits
-- """""""""""""""""""""""""

-- hi ( "Underlined", {} )
-- hi ( "RedrawDebugNormal", {} )

-- "" treesitter
-- hi ( "@attribute", {} )
-- hi ( "@attribute.builtin", {} )
hi("@boolean", { link = 'Boolean' })
hi("@character", { link = 'Character' })
hi("@character.special", { link = 'SpecialChar' })
hi("@comment", { link = 'Comment' })
-- hi ( "@comment.error", {} )
-- hi ( "@comment.note", {} )
hi("@comment.todo", { link = 'Todo' })
-- hi ( "@comment.warning", {} )
hi("@constant", { link = 'Constant' })
-- hi ( "@constant.builtin", {} )
-- hi ( "@constant.macro", {} )
-- hi ( "@constructor", {} )
hi("@diff.delta", { link = 'DiffChange' })
hi("@diff.minus", { link = 'DiffDelete' })
hi("@diff.plus", { link = 'DiffAdd' })
hi("@function", { link = 'Function' })
-- hi ( "@function.builtin", {} )
-- hi ( "@function.method", {} )
hi("@keyword", { link = 'Keyword' })
hi("@label", { link = 'Label' })
-- hi ( "@markup", {} )
-- hi ( "@markup.heading", {} )
-- hi ( "@markup.italic", {} )
-- hi ( "@markup.link", {} )
-- hi ( "@markup.strikethrough", {} )
-- hi ( "@markup.strong", {} )
-- hi ( "@markup.underline", {} )
-- hi ( "@module", {} )
-- hi ( "@module.builtin", {} )
hi("@number", { link = 'Number' })
hi("@number.float", { link = 'Float' })
hi("@operator", { link = 'Operator' })
-- hi ( "@property", {} )
hi("@punctuation", { link = '@ncf.punctuation' })
-- hi ( "@punctuation.special", {} )
hi("@string", { link = 'String' })
-- hi ( "@string.escape", {} )
-- hi ( "@string.regexp", {} )
-- hi ( "@string.special", {} )
-- hi ( "@string.special.url", {} )
hi("@tag", { link = 'Tag' })
-- hi ( "@tag.builtin", {} )
hi("@type", { link = 'Type' })
hi("@type.builtin", { link = '@type' })
hi("@type.definition", { link = '@type' })
hi("@type.qualifier", { link = '@type' })
hi("@variable", { link = 'Identifier' })
hi("@variable.builtin", { link = '@variable' })
hi("@variable.parameter", { link = '@variable' })
hi("@variable.parameter.builtin", { link = '@variable' })

-- "" ( "LSP" syntax highlighting )
-- hi ( "@lsp.mod.deprecated", {} )
-- hi ( "@lsp.type.class", {} )
-- hi ( "@lsp.type.comment", {} )
-- hi ( "@lsp.type.decorator", {} )
-- hi ( "@lsp.type.enum", {} )
-- hi ( "@lsp.type.enumMember", {} )
-- hi ( "@lsp.type.event", {} )
-- hi ( "@lsp.type.function", {} )
-- hi ( "@lsp.type.interface", {} )
-- hi ( "@lsp.type.keyword", {} )
-- hi ( "@lsp.type.macro", {} )
-- hi ( "@lsp.type.method", {} )
-- hi ( "@lsp.type.modifier", {} )
-- hi ( "@lsp.type.namespace", {} )
-- hi ( "@lsp.type.number", {} )
-- hi ( "@lsp.type.operator", {} )
-- hi ( "@lsp.type.parameter", {} )
-- hi ( "@lsp.type.property", {} )
-- hi ( "@lsp.type.regexp", {} )
-- hi ( "@lsp.type.string", {} )
-- hi ( "@lsp.type.struct", {} )
-- hi ( "@lsp.type.type", {} )
-- hi ( "@lsp.type.typeParameter", {} )
-- hi ( "@lsp.type.variable", {} )

-- "" :help
-- hi ( "@markup.heading.1.delimiter.vimdoc", {} )
-- hi ( "@markup.heading.2.delimiter.vimdoc", {} )

-- "" UI
-- hi ( "Added", {} )
-- hi ( "Changed", {} )
-- hi ( "CursorIM", {} )
-- hi ( "FloatShadow", {} )
-- hi ( "FloatShadowThrough", {} )
-- hi ( "RedrawDebugClear", {} )
-- hi ( "RedrawDebugComposed", {} )
-- hi ( "RedrawDebugRecompose", {} )
-- hi ( "Removed", {} )
-- hi ( "Substitute", {} )

-- "" Syntax
-- hi("Boolean", {})
-- hi("Character", {})
hi("Comment", { link = '@ncf.comment' })
-- hi("Conditional", {})
hi("Constant", { link = '@ncf.constant' })
-- hi("Debug", {})
-- hi("Define", {})
-- hi("Delimiter", {})
-- hi("Error", {})
-- hi("Exception", {})
-- hi("Float", {})
hi("Function", { link = '@ncf.function' })
hi("Identifier", { link = '@ncf.variable' })
-- hi("Ignore", {})
-- hi("Include", {})
hi("Keyword", { link = '@ncf.keyword' })
hi("Label", { link = '@ncf.label' })
-- hi("Macro", {})
-- hi("Number", {})
hi("Operator", { link = '@ncf.operator' })
-- hi("PreCondit", {})
-- hi("PreProc", {})
-- hi("Repeat", {})
-- hi("Special", {})
-- hi("SpecialChar", {})
-- hi("SpecialComment", {})
-- hi("Statement", {})
-- hi("StorageClass", {})
hi("String", { link = '@ncf.string' })
-- hi("Structure", {})
hi("Tag", { link = '@ncf.tag' })
-- hi("Todo", {})
hi("Type", { link = '@ncf.type' })
-- hi("Typedef", {})

-- "" Diagnostic
-- hi ( "DiagnosticDeprecated", { link = '@ncf.diagnostic.warning' } )
-- hi ( "DiagnosticError", { link = '@ncf.diagnostic.error' } )
-- hi ( "DiagnosticFloatingError", {} )
-- hi ( "DiagnosticFloatingHint", {} )
-- hi ( "DiagnosticFloatingInfo", {} )
-- hi ( "DiagnosticFloatingOk", {} )
-- hi ( "DiagnosticFloatingWarn", {} )
-- hi ( "DiagnosticHint", { link = '@ncf.diagnostic.hint' } )
-- hi ( "DiagnosticInfo", { link = '@ncf.diagnostic.info' } )
-- hi ( "DiagnosticOk", {} )
-- hi ( "DiagnosticSignError", {} )
-- hi ( "DiagnosticSignHint", {} )
-- hi ( "DiagnosticSignInfo", {} )
-- hi ( "DiagnosticSignOk", {} )
-- hi ( "DiagnosticSignWarn", {} )
-- hi ( "DiagnosticUnderlineError", {} )
-- hi ( "DiagnosticUnderlineHint", {} )
-- hi ( "DiagnosticUnderlineInfo", {} )
-- hi ( "DiagnosticUnderlineOk", {} )
-- hi ( "DiagnosticUnderlineWarn", {} )
-- hi ( "DiagnosticUnnecessary", { link = '@ncf.diagnostic.unnecessary' } )
-- hi ( "DiagnosticVirtualLinesError", {} )
-- hi ( "DiagnosticVirtualLinesHint", {} )
-- hi ( "DiagnosticVirtualLinesInfo", {} )
-- hi ( "DiagnosticVirtualLinesOk", {} )
-- hi ( "DiagnosticVirtualLinesWarn", {} )
-- hi ( "DiagnosticVirtualTextError", {} )
-- hi ( "DiagnosticVirtualTextHint", {} )
-- hi ( "DiagnosticVirtualTextInfo", {} )
-- hi ( "DiagnosticVirtualTextOk", {} )
-- hi ( "DiagnosticVirtualTextWarn", {} )
-- hi ( "DiagnosticWarn", { link = '@ncf.diagnostic.warning' } )

-- "" Built-in LSP
-- hi ( "LspCodeLens", {} )
-- hi ( "LspCodeLensSeparator", {} )
-- hi ( "LspInlayHint", {} )
-- hi ( "LspReferenceRead", {} )
-- hi ( "LspReferenceTarget", {} )
-- hi ( "LspReferenceText", {} )
-- hi ( "LspReferenceWrite", {} )
-- hi ( "LspSignatureActiveParameter", {} )
-- hi ( "SnippetTabstop", {} )

-- "" Neovim parser
-- hi ( "NvimAnd", {} )
-- hi ( "NvimArrow", {} )
-- hi ( "NvimAssignment", {} )
-- hi ( "NvimAssignmentWithAddition", {} )
-- hi ( "NvimAssignmentWithConcatenation", {} )
-- hi ( "NvimAssignmentWithSubtraction", {} )
-- hi ( "NvimAugmentedAssignment", {} )
-- hi ( "NvimBinaryMinus", {} )
-- hi ( "NvimBinaryOperator", {} )
-- hi ( "NvimBinaryPlus", {} )
-- hi ( "NvimCallingParenthesis", {} )
-- hi ( "NvimColon", {} )
-- hi ( "NvimComma", {} )
-- hi ( "NvimComparison", {} )
-- hi ( "NvimComparisonModifier", {} )
-- hi ( "NvimConcat", {} )
-- hi ( "NvimConcatOrSubscript", {} )
-- hi ( "NvimContainer", {} )
-- hi ( "NvimCurly", {} )
-- hi ( "NvimDict", {} )
-- hi ( "NvimDivision", {} )
-- hi ( "NvimDoubleQuote", {} )
-- hi ( "NvimDoubleQuotedBody", {} )
-- hi ( "NvimDoubleQuotedEscape", {} )
-- hi ( "NvimDoubleQuotedUnknownEscape", {} )
-- hi ( "NvimEnvironmentName", {} )
-- hi ( "NvimEnvironmentSigil", {} )
-- hi ( "NvimFigureBrace", {} )
-- hi ( "NvimFloat", {} )
-- hi ( "NvimIdentifier", {} )
-- hi ( "NvimIdentifierKey", {} )
-- hi ( "NvimIdentifierName", {} )
-- hi ( "NvimIdentifierScope", {} )
-- hi ( "NvimIdentifierScopeDelimiter", {} )
-- hi ( "NvimInternalError", {} )
-- hi ( "NvimInvalid", {} )
-- hi ( "NvimInvalidAnd", {} )
-- hi ( "NvimInvalidArrow", {} )
-- hi ( "NvimInvalidAssignment", {} )
-- hi ( "NvimInvalidAssignmentWithAddition", {} )
-- hi ( "NvimInvalidAssignmentWithConcatenation", {} )
-- hi ( "NvimInvalidAssignmentWithSubtraction", {} )
-- hi ( "NvimInvalidAugmentedAssignment", {} )
-- hi ( "NvimInvalidBinaryMinus", {} )
-- hi ( "NvimInvalidBinaryOperator", {} )
-- hi ( "NvimInvalidBinaryPlus", {} )
-- hi ( "NvimInvalidCallingParenthesis", {} )
-- hi ( "NvimInvalidColon", {} )
-- hi ( "NvimInvalidComma", {} )
-- hi ( "NvimInvalidComparison", {} )
-- hi ( "NvimInvalidComparisonModifier", {} )
-- hi ( "NvimInvalidConcat", {} )
-- hi ( "NvimInvalidConcatOrSubscript", {} )
-- hi ( "NvimInvalidContainer", {} )
-- hi ( "NvimInvalidCurly", {} )
-- hi ( "NvimInvalidDelimiter", {} )
-- hi ( "NvimInvalidDict", {} )
-- hi ( "NvimInvalidDivision", {} )
-- hi ( "NvimInvalidDoubleQuote", {} )
-- hi ( "NvimInvalidDoubleQuotedBody", {} )
-- hi ( "NvimInvalidDoubleQuotedEscape", {} )
-- hi ( "NvimInvalidDoubleQuotedUnknownEscape", {} )
-- hi ( "NvimInvalidEnvironmentName", {} )
-- hi ( "NvimInvalidEnvironmentSigil", {} )
-- hi ( "NvimInvalidFigureBrace", {} )
-- hi ( "NvimInvalidFloat", {} )
-- hi ( "NvimInvalidIdentifier", {} )
-- hi ( "NvimInvalidIdentifierKey", {} )
-- hi ( "NvimInvalidIdentifierName", {} )
-- hi ( "NvimInvalidIdentifierScope", {} )
-- hi ( "NvimInvalidIdentifierScopeDelimiter", {} )
-- hi ( "NvimInvalidLambda", {} )
-- hi ( "NvimInvalidList", {} )
-- hi ( "NvimInvalidMod", {} )
-- hi ( "NvimInvalidMultiplication", {} )
-- hi ( "NvimInvalidNestingParenthesis", {} )
-- hi ( "NvimInvalidNot", {} )
-- hi ( "NvimInvalidNumber", {} )
-- hi ( "NvimInvalidNumberPrefix", {} )
-- hi ( "NvimInvalidOperator", {} )
-- hi ( "NvimInvalidOptionName", {} )
-- hi ( "NvimInvalidOptionScope", {} )
-- hi ( "NvimInvalidOptionScopeDelimiter", {} )
-- hi ( "NvimInvalidOptionSigil", {} )
-- hi ( "NvimInvalidOr", {} )
-- hi ( "NvimInvalidParenthesis", {} )
-- hi ( "NvimInvalidPlainAssignment", {} )
-- hi ( "NvimInvalidRegister", {} )
-- hi ( "NvimInvalidSingleQuote", {} )
-- hi ( "NvimInvalidSingleQuotedBody", {} )
-- hi ( "NvimInvalidSingleQuotedQuote", {} )
-- hi ( "NvimInvalidSingleQuotedUnknownEscape", {} )
-- hi ( "NvimInvalidSpacing", {} )
-- hi ( "NvimInvalidString", {} )
-- hi ( "NvimInvalidStringBody", {} )
-- hi ( "NvimInvalidStringQuote", {} )
-- hi ( "NvimInvalidStringSpecial", {} )
-- hi ( "NvimInvalidSubscript", {} )
-- hi ( "NvimInvalidSubscriptBracket", {} )
-- hi ( "NvimInvalidSubscriptColon", {} )
-- hi ( "NvimInvalidTernary", {} )
-- hi ( "NvimInvalidTernaryColon", {} )
-- hi ( "NvimInvalidUnaryMinus", {} )
-- hi ( "NvimInvalidUnaryOperator", {} )
-- hi ( "NvimInvalidUnaryPlus", {} )
-- hi ( "NvimInvalidValue", {} )
-- hi ( "NvimLambda", {} )
-- hi ( "NvimList", {} )
-- hi ( "NvimMod", {} )
-- hi ( "NvimMultiplication", {} )
-- hi ( "NvimNestingParenthesis", {} )
-- hi ( "NvimNot", {} )
-- hi ( "NvimNumber", {} )
-- hi ( "NvimNumberPrefix", {} )
-- hi ( "NvimOperator", {} )
-- hi ( "NvimOptionName", {} )
-- hi ( "NvimOptionScope", {} )
-- hi ( "NvimOptionScopeDelimiter", {} )
-- hi ( "NvimOptionSigil", {} )
-- hi ( "NvimOr", {} )
-- hi ( "NvimParenthesis", {} )
-- hi ( "NvimPlainAssignment", {} )
-- hi ( "NvimRegister", {} )
-- hi ( "NvimSingleQuote", {} )
-- hi ( "NvimSingleQuotedBody", {} )
-- hi ( "NvimSingleQuotedQuote", {} )
-- hi ( "NvimSingleQuotedUnknownEscape", {} )
-- hi ( "NvimSpacing", {} )
-- hi ( "NvimString", {} )
-- hi ( "NvimStringBody", {} )
-- hi ( "NvimStringQuote", {} )
-- hi ( "NvimStringSpecial", {} )
-- hi ( "NvimSubscript", {} )
-- hi ( "NvimSubscriptBracket", {} )
-- hi ( "NvimSubscriptColon", {} )
-- hi ( "NvimTernary", {} )
-- hi ( "NvimTernaryColon", {} )
-- hi ( "NvimUnaryMinus", {} )
-- hi ( "NvimUnaryOperator", {} )
-- hi ( "NvimUnaryPlus", {} )
